#!/usr/bin/env ruby

number = 123

puts "What number am I thinking of?"

loop do
  guess = gets

  break if guess.nil?

  guess.chomp!

  if guess.to_i == number
    puts "\e[0;32;1mYeah\e[0m, it's \e[0;1m#{number}\e[0m!"
    break
  end

  puts "\e[0;31;1mNope\e[0m, it's not \e[0;1m#{guess}\e[0m. Try again!"
end
