version: '3.6'
services:

  license_finder:
    build:
      dockerfile: dockerfiles/Dockerfile.audit
      context: .
    volumes:
      - ./:/scan

  ci-ruby-3:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: ci-ruby-3

  ci-ruby-2:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: ci-ruby-2
    environment:
      USE_LEGACY_DRIVER: 1

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: cli

  cli-legacy:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: cli-legacy

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:

  android-appium-test:
    build:
      context: test/fixtures/android-appium-test
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_DEVICES_USERNAME:
      BROWSER_STACK_DEVICES_ACCESS_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_TMS_URI:
    env_file: $DOCKER_ENV_FILE
    volumes:
      - ./test/fixtures/android-appium-test/app/build:/app/build
      - ./test/fixtures/android-appium-test/features:/app/features
      - ./test/fixtures/android-appium-test/maze_output:/app/maze_output

  android-appium-test-bitbar:
    build:
      context: test/fixtures/android-appium-test
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_PIPELINE_SLUG:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_TMS_URI:
    env_file: $DOCKER_ENV_FILE
    ports:
      - "9000-9499:9339"
    volumes:
      - ./test/fixtures/android-appium-test/app/build:/app/build
      - ./test/fixtures/android-appium-test/features:/app/features
      - ./test/fixtures/android-appium-test/maze_output:/app/maze_output
      - /var/run/docker.sock:/var/run/docker.sock

  android-appium-test-legacy:
    build:
      context: test/fixtures/android-appium-test
      dockerfile: Dockerfile.legacy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE:
      BUILDKITE_BRANCH:
      BUILDKITE_BUILD_CREATOR:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_BUILD_URL:
      BUILDKITE_LABEL:
      BUILDKITE_MESSAGE:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_REPO:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE_STEP_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_DEVICES_USERNAME:
      BROWSER_STACK_DEVICES_ACCESS_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_TMS_URI:
      USE_LEGACY_DRIVER: 1
    env_file: $DOCKER_ENV_FILE
    volumes:
      - ./test/fixtures/android-appium-test/app/build:/app/build
      - ./test/fixtures/android-appium-test/features:/app/features
      - ./test/fixtures/android-appium-test/maze_output:/app/maze_output

  ios-appium-test:
    build:
      context: test/fixtures/ios-app
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_DEVICES_USERNAME:
      BROWSER_STACK_DEVICES_ACCESS_KEY:
      MAZE_BUGSNAG_API_KEY:
      MAZE_TMS_URI:
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
    env_file: $DOCKER_ENV_FILE
    volumes:
      - ./test/fixtures/ios-app/maze_output:/app/maze_output

  cli-tests:
    build:
      context: test/fixtures/cli
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  doc-server-tests:
    build:
      context: test/fixtures/doc-server
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  exit-codes-tests:
    build:
      context: test/fixtures/exit-codes
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  framework-tests:
    build:
      context: test/fixtures/framework
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  docker-tests:
    build:
      context: test/fixtures/docker-app
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-core-maze-runner}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy-tests:
    build:
      context: test/fixtures/proxy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
    volumes:
      - ./test/fixtures/payload-helpers/maze_output:/app/maze_output

  http-response-tests:
    build:
      context: test/fixtures/http-response
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:

  unit-test-ruby-2:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: unit-test-ruby-2
    environment:
      USE_LEGACY_DRIVER: 1

  unit-test-ruby-3:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: unit-test-ruby-3

  browser-tests:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BUILDKITE:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_BROWSERS_USERNAME:
      BROWSER_STACK_BROWSERS_ACCESS_KEY:
      MAZE_TMS_URI:
      MAZE_TMS_TOKEN:
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}
    ports:
      - "9000-9499:9339"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  browser-tests-legacy:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.legacy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BUILDKITE:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_BROWSERS_USERNAME:
      BROWSER_STACK_BROWSERS_ACCESS_KEY:
      MAZE_TMS_URI:
      MAZE_TMS_TOKEN:
      USE_LEGACY_DRIVER: 1
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}

  browser-tests-bitbar:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_LABEL:
      BUILDKITE_PIPELINE_SLUG:
      BUILDKITE_RETRY_COUNT:
      MAZE_TMS_URI:
      MAZE_TMS_TOKEN:
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}
    ports:
      - "9000-9499:9339"
      - "9000-9499:9340"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-core-maze-runner}
