version: '3.4'
services:
  ci:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: ci

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: cli

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:

  browserstack-app-automate:
    build:
      context: test/fixtures/browserstack-app
      args:
        BUILDKITE_BRANCH:
    environment:
      BUILDKITE_BRANCH:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BUILDKITE_BRANCH:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME: