version: '3.6'

x-common-environment: &common-environment
  DEBUG:
  BRANCH_NAME:
  BUILDKITE:
  BUILDKITE_BRANCH:
  BUILDKITE_BUILD_CREATOR:
  BUILDKITE_BUILD_NUMBER:
  BUILDKITE_BUILD_URL:
  BUILDKITE_JOB_ID:
  BUILDKITE_LABEL:
  BUILDKITE_MESSAGE:
  BUILDKITE_PIPELINE_NAME:
  BUILDKITE_PIPELINE_SLUG:
  BUILDKITE_REPO:
  BUILDKITE_RETRY_COUNT:
  BUILDKITE_STEP_KEY:
  MAZE_BUGSNAG_API_KEY:
  MAZE_SCENARIO_BUGSNAG_API_KEY:

services:

  license_finder:
    build:
      dockerfile: dockerfiles/Dockerfile.audit
      context: .
    volumes:
      - ./:/scan

  ci-ruby-3:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: ci-ruby-3

  ci-ruby-2:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: ci-ruby-2
    environment:
      USE_LEGACY_DRIVER: 1

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: cli

  cli-legacy:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: cli-legacy

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:
    environment:
      BUILDKITE_TAG:
      DOCS_PUSH_TOKEN:

  appium-test-bb:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      <<: *common-environment
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
    env_file: $DOCKER_ENV_FILE
    ports:
      - "9000-9499:9339"
      - "9000-9499:9340"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  appium-test-bs:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      <<: *common-environment
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_DEVICES_USERNAME:
      BROWSER_STACK_DEVICES_ACCESS_KEY:
    env_file: $DOCKER_ENV_FILE

  appium-test-bs-legacy:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.legacy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      <<: *common-environment
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_DEVICES_USERNAME:
      BROWSER_STACK_DEVICES_ACCESS_KEY:
      USE_LEGACY_DRIVER: 1
    env_file: $DOCKER_ENV_FILE

  cli-tests:
    build:
      context: test/fixtures/cli
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  doc-server-tests:
    build:
      context: test/fixtures/doc-server
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  exit-codes-tests:
    build:
      context: test/fixtures/exit-codes
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  framework-tests:
    build:
      context: test/fixtures/framework
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  docker-tests:
    build:
      context: test/fixtures/docker-app
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy-tests:
    build:
      context: test/fixtures/proxy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:
    volumes:
      - ./test/fixtures/payload-helpers/maze_output:/app/maze_output

  command-workflow-tests:
    build:
      context: test/fixtures/command-workflow
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:
    volumes:
      - ./test/fixtures/command-workflow/maze_output:/app/maze_output

  http-response-tests:
    build:
      context: test/fixtures/http-response
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      MAZE_BUGSNAG_API_KEY:
      USE_LEGACY_DRIVER:

  unit-test-ruby-2:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-2
      context: .
      target: unit-test-ruby-2
    environment:
      USE_LEGACY_DRIVER: 1

  unit-test-ruby-3:
    build:
      dockerfile: dockerfiles/Dockerfile.ci-ruby-3
      context: .
      target: unit-test-ruby-3

  browser-tests:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BUILDKITE:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_BROWSERS_USERNAME:
      BROWSER_STACK_BROWSERS_ACCESS_KEY:
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}
    ports:
      - "9000-9499:9339"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  browser-tests-legacy:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.legacy
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BUILDKITE:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_BROWSERS_USERNAME:
      BROWSER_STACK_BROWSERS_ACCESS_KEY:
      USE_LEGACY_DRIVER: 1
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}

  browser-tests-bitbar:
    build:
      context: test/fixtures/browser
      dockerfile: Dockerfile.w3c
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      BITBAR_USERNAME:
      BITBAR_ACCESS_KEY:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_LABEL:
      BUILDKITE_PIPELINE_SLUG:
      BUILDKITE_RETRY_COUNT:
    env_file:
      - ${DOCKER_ENV_FILE:-test/browser/features/fixtures/null_env}
    ports:
      - "9000-9499:9339"
      - "9000-9499:9340"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-core-maze-runner}
