version: '3.6'
services:

  license_finder:
    build:
      dockerfile: dockerfiles/Dockerfile.audit
      context: .
    volumes:
      - ./:/scan

  ci:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: ci
      args:
        - RUBY_VERSION

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: cli

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:

  android-appium-test:
    build:
      context: test/fixtures/android-appium-test
      args:
        BRANCH_NAME:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:
    volumes:
      - ./test/fixtures/android-appium-test/maze_output:/app/maze_output

  ios-appium-test:
    build:
      context: test/fixtures/ios-app
      args:
        BRANCH_NAME:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:
    volumes:
      - ./test/fixtures/ios-app/maze_output:/app/maze_output

  cli-tests:
    build:
      context: test/fixtures/cli
      args:
        BRANCH_NAME:

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  doc-server-tests:
    build:
      context: test/fixtures/doc-server
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  framework-tests:
    build:
      context: test/fixtures/framework
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  docker-tests:
    build:
      context: test/fixtures/docker-app
      args:
        BRANCH_NAME:
        RUBY_VERSION:
    environment:
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-core-maze-runner}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy-tests:
    build:
      context: test/fixtures/proxy
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  http-response-tests:
    build:
      context: test/fixtures/http-response
      args:
        BRANCH_NAME:
        RUBY_VERSION:

  unit-test:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: unit-test
      args:
        RUBY_VERSION:

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-core-maze-runner}
