version: '3.4'
services:
  ci:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: ci

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: cli

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:

  browserstack-app-automate:
    build:
      context: test/fixtures/browserstack-app
      args:
        BRANCH_NAME:
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BRANCH_NAME:

  framework-tests:
    build:
      context: test/fixtures/framework
      args:
        BRANCH_NAME:

  proxy-tests:
    build:
      context: test/fixtures/proxy
      args:
        BRANCH_NAME:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME:

  http-response-tests:
    build:
      context: test/fixtures/http-response
      args:
        BRANCH_NAME:

  unit-test:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: unit-test
