version: '3.6'
services:
  ci:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: ci

  cli:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: cli

  docs:
    build:
      dockerfile: dockerfiles/Dockerfile.docs
      context: .
      args:
        DOCS_PUSH_TOKEN:

  android-appium-test:
    build:
      context: test/fixtures/android-appium-test
      args:
        BRANCH_NAME:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:
      MAZE_DEVICE_FARM_USERNAME:
      MAZE_DEVICE_FARM_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:

  ios-appium-test:
    build:
      context: test/fixtures/ios-app
      args:
        BRANCH_NAME:
    extra_hosts:
      - "maze-local:127.0.0.1"
    environment:
      BRANCH_NAME:
      BUILDKITE_PIPELINE_NAME:
      BUILDKITE_RETRY_COUNT:
      BUILDKITE:
      BUILDKITE_BUILD_NUMBER:
      BUILDKITE_STEP_KEY:
      MAZE_DEVICE_FARM_USERNAME:
      MAZE_DEVICE_FARM_ACCESS_KEY:
      SAUCE_LABS_USERNAME:
      SAUCE_LABS_ACCESS_KEY:

  cli-tests:
    build:
      context: test/fixtures/cli
      args:
        BRANCH_NAME:

  comparison-tests:
    build:
      context: test/fixtures/comparison
      args:
        BRANCH_NAME:

  framework-tests:
    build:
      context: test/fixtures/framework
      args:
        BRANCH_NAME:

  docker-tests:
    build:
      context: test/fixtures/docker-app
      args:
        BRANCH_NAME:
    environment:
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-core-maze-runner}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  proxy-tests:
    build:
      context: test/fixtures/proxy
      args:
        BRANCH_NAME:

  payload-helper-tests:
    build:
      context: test/fixtures/payload-helpers
      args:
        BRANCH_NAME:

  http-response-tests:
    build:
      context: test/fixtures/http-response
      args:
        BRANCH_NAME:

  unit-test:
    build:
      dockerfile: dockerfiles/Dockerfile.ci
      context: .
      target: unit-test

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-core-maze-runner}
