version: '3.4'
services:
  ci:
    build:
      context: .
      target: ci

  cli:
    build:
      context: .
      target: cli

  browserstack-app-automate:
    build:
      context: test/fixtures/browserstack-app
      args:
        BUILDKITE_BRANCH:
    environment:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}