steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    command: ./scripts/license_finder.sh

  - label: 'AWS - SAM tests'
    timeout_in_minutes: 30
    agents:
      queue: 'opensource-mac-aws-sam'
    command: >-
      cd test/fixtures/aws-sam &&
      bundle install &&
      bundle exec maze-runner
      --no-log-requests

  - label: 'Build Appium test fixture'
    timeout_in_minutes: 30
    key: appium-test-fixture
    agents:
      queue: 'macos-12-arm'
    command:
      - cd test/fixtures/android-appium-test
      - ./gradlew assembleRelease
    plugins:
      artifacts#v1.5.0:
        upload: "test/fixtures/android-appium-test/app/build/outputs/apk/release/app-release.apk"

  - label: ':docker: Build CI image for Ruby 2.7'
    timeout_in_minutes: 30
    key: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v3.7.0:
          build:
            - ci-ruby-2.7
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
      - docker-compose#v3.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
    env:
      RUBY_VERSION: "2.7"

  - label: ':docker: Build CI image for Ruby 3'
    timeout_in_minutes: 30
    key: "ci-image-ruby-3"
    plugins:
      - docker-compose#v3.7.0:
          build:
            - ci-ruby-3
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
      - docker-compose#v3.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
    env:
      RUBY_VERSION: "3"

  - label: 'Unit tests with Ruby 2.7'
    timeout_in_minutes: 30
    depends_on: 'ci-image-ruby-2-7'
    plugins:
      docker-compose#v3.7.0:
        run: unit-test
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
        cache-from:
          - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
    env:
      RUBY_VERSION: "2.7"
    command: 'bundle exec rake'

  - label: 'Unit tests with Ruby 3'
    timeout_in_minutes: 30
    depends_on: 'ci-image-ruby-3'
    plugins:
      docker-compose#v3.7.0:
        run: unit-test
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
        cache-from:
          - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
    env:
      RUBY_VERSION: "3"
    command: 'bundle exec rake'

  - label: ':docker: Push W3C Docker image for branch'
    key: push-branch-cli
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v3.7.0:
          build: cli
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - label: ':docker: Push Legacy Docker image for branch'
    key: push-branch-legacy-cli
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v3.7.0:
          build: cli-legacy
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli-legacy
      - docker-compose#v3.7.0:
          push:
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli-legacy

  - label: 'No-device tests with Ruby 2.7'
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v3.7.0:
          run: framework-tests
      - docker-compose#v3.7.0:
          run: comparison-tests
      - docker-compose#v3.7.0:
          run: proxy-tests
      - docker-compose#v3.7.0:
          run: cli-tests
      - docker-compose#v3.7.0:
          run: http-response-tests
      - docker-compose#v3.7.0:
          run: payload-helper-tests
      - docker-compose#v3.7.0:
          run: docker-tests
      - docker-compose#v3.7.0:
          run: doc-server-tests
      - docker-compose#v3.7.0:
          run: exit-codes-tests
    env:
      RUBY_VERSION: "2.7"
    command: 'bundle exec maze-runner -e features/fixtures'

  - label: 'No-device tests with Ruby 3'
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-3"
    plugins:
      - docker-compose#v3.7.0:
          run: framework-tests
      - docker-compose#v3.7.0:
          run: comparison-tests
      - docker-compose#v3.7.0:
          run: proxy-tests
      - docker-compose#v3.7.0:
          run: cli-tests
      - docker-compose#v3.7.0:
          run: http-response-tests
      - docker-compose#v3.7.0:
          run: payload-helper-tests
      - docker-compose#v3.7.0:
          run: docker-tests
      - docker-compose#v3.7.0:
          run: doc-server-tests
      - docker-compose#v3.7.0:
          run: exit-codes-tests
    env:
      RUBY_VERSION: "3"
    command: 'bundle exec maze-runner -e features/fixtures'

  - label: 'BrowserStack app-automate - Android 7 - JWP'
    timeout_in_minutes: 20
    depends_on:
      - "appium-test-fixture"
      - "push-branch-legacy-cli"
    plugins:
      artifacts#v1.5.0:
        download: "test/fixtures/android-appium-test/app/build/outputs/apk/release/app-release.apk"
      docker-compose#v3.7.0:
        pull: android-appium-test-legacy
        run: android-appium-test-legacy
        command:
          - "--app=build/outputs/apk/release/app-release.apk"
          - "--farm=bs"
          - "--device=ANDROID_7_1"
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
        cache-from:
          - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli-legacy
      artifacts#v1.3.0:
        upload: test/fixtures/android-appium-test/maze_output/**/*
    env:
      RUBY_VERSION: "2.7"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
    # PLAT-9240: Soft fail pending resolution of BrowserStack secure tunnel outage
    soft_fail:
      - exit_status: 1

  - label: 'BrowserStack app-automate - Android 13 - W3C'
    timeout_in_minutes: 20
    depends_on:
      - "appium-test-fixture"
      - "push-branch-cli"
    plugins:
      artifacts#v1.5.0:
        download: "test/fixtures/android-appium-test/app/build/outputs/apk/release/app-release.apk"
      docker-compose#v3.7.0:
        pull: android-appium-test
        run: android-appium-test
        command:
          - "--app=build/outputs/apk/release/app-release.apk"
          - "--farm=bs"
          - "--device=ANDROID_13_0"
        image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
        cache-from:
          - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      artifacts#v1.3.0:
        upload: test/fixtures/android-appium-test/maze_output/**/*
    env:
      RUBY_VERSION: "3"
    concurrency: 24
    concurrency_group: 'browserstack-app'
    concurrency_method: eager

  - label: 'Browserstack web browser test - Latest Firefox'
    depends_on: "ci-image-ruby-2-7"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.7.0:
        run: browser-tests
        use-aliases: true
        verbose: true
    command: >-
      bundle exec maze-runner
      --farm=bs
      --browser=firefox_latest
    env:
      RUBY_VERSION: "2.7"
    concurrency: 2
    concurrency_group: 'browserstack'

  - label: 'BitBar web browser test - Firefox v104'
    depends_on: "ci-image-ruby-2-7"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.7.0:
        run: browser-tests
        use-aliases: true
        verbose: true
    command: >-
      bundle exec maze-runner
      --farm=bb
      --browser=firefox_104
    env:
      RUBY_VERSION: "2.7"
    concurrency: 2
    concurrency_group: 'bitbar-web'

  - wait

  - label: 'Update docs'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      docker-compose#v3.7.0:
        run: docs
    command: 'bundle exec rake docs:build_and_publish'

    # Release images are pushed to their own repository so that they don't get aged off.
  - label: 'Push Docker image for tag'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v7-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli-legacy
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v7-cli-legacy
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli-legacy
