steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v3.7.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci
      - docker-compose#v3.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - wait

  - label: ':docker: Build test images'
    plugins:
      - docker-compose#v3.7.0:
          build:
            - comparison-tests
            - browserstack-app-automate
            - payload-helper-tests
            - http-response-tests
            - unit-test
            - docker-tests
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci
          build-parallel: true

  - wait

  - label: 'Unit tests'
    plugins:
      docker-compose#v3.7.0:
        run: unit-test
    command: 'bundle exec rake'

  - label: 'No-device tests'
    plugins:
      - docker-compose#v3.7.0:
          run: framework-tests
      - docker-compose#v3.7.0:
          run: comparison-tests
      - docker-compose#v3.7.0:
          run: proxy-tests
      - docker-compose#v3.7.0:
          run: http-response-tests
      - docker-compose#v3.7.0:
          run: payload-helper-tests
    command: 'bundle exec maze-runner'

  - label: 'Browserstack app-automate test - Android 6'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_6_0
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 7.1 (separate Appium sessions)'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_7_1
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 8.1'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --resilient
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_8_1
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 9'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_9_0
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 10 (separate Appium sessions)'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_10_0
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
      --appium-version=1.17.0
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 11 (separate Appium sessions)'
    plugins:
      docker-compose#v3.7.0:
        run: browserstack-app-automate
    command: >-
      bundle exec bugsnag-maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_11_0
      --username=$BROWSER_STACK_USERNAME
      --access-key=$BROWSER_STACK_ACCESS_KEY
      --appium-version=1.17.0
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - wait

  - label: 'Push Docker image for branch'
    plugins:
      - docker-compose#v3.7.0:
          build: cli
          cache-from: cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - wait

  - label: 'Trigger Android build against new master'
    branches: 'master'
    trigger: 'android-bugsnag-notifier'
    build:
      branch: 'maze-runner-master'
    async: true

  - label: 'Trigger Cocoa build against new master'
    branches: 'master'
    trigger: 'cocoa-bugsnag-notifier'
    build:
      branch: 'maze-runner-master'
    async: true

  - label: 'Trigger JS build against new master'
    branches: 'master'
    trigger: 'at-bugsnag-js'
    build:
      branch: 'maze-runner-master'
    async: true

  - label: 'Update docs'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      docker-compose#v3.7.0:
        run: docs
    command: 'bundle exec rake docs:build_and_publish'

    # Release images are pushed to their own repository so that they don't get aged off.
  - label: 'Push Docker image for tag'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v3-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli
