steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v3.3.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-ci
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - wait

  - label: ':docker: Push CI'
    plugins:
      - docker-compose#v3.3.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-ci
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - wait

  - label: ':docker: Build test images'
    plugins:
      - docker-compose#v3.3.0:
          build:
            - comparison-tests
            - browserstack-app-automate
            - payload-helper-tests
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          build-parallel: true

  - wait

  - label: 'Unit tests'
    plugins:
      docker-compose#v3.3.0:
        run: ci
    command: 'bundle exec rake'

  - label: 'Comparison tests'
    plugins:
      docker-compose#v3.3.0:
        run: comparison-tests
    command: 'bundle exec bugsnag-maze-runner'

  - label: 'Browserstack-app-automate integration test'
    plugins:
      docker-compose#v3.3.0:
        run: browserstack-app-automate
    command: 'bundle exec bugsnag-maze-runner'
    concurrency: 10
    concurrency_group: 'browserstack-app'

  - label: 'Payload helper tests'
    plugins:
      docker-compose#v3.3.0:
        run: payload-helper-tests
    command: 'bundle exec bugsnag-maze-runner'

  - wait

  - label: 'Push Docker image for branch'
    plugins:
      - docker-compose#v3.3.0:
          build: cli
          cache-from: cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v3.3.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - label: 'Update docs'
    if: build.tag =~ /^v2\.[0-9]+\.[0-9]+\$/
    plugins:
      docker-compose#v3.3.0:
        run: docs
    command: 'bundle exec rake docs:build_and_publish'

  - label: 'Push Docker image for tag'
    if: build.tag =~ /^v2\.[0-9]+\.[0-9]+\$/
    plugins:
      - docker-compose#v3.3.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BUILDKITE_TAG}-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-cli

