steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    command: ./scripts/license_finder.sh

  - label: 'Run the test'
    timeout_in_minutes: 30
    key: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v4.7.0:
          build:
            - ci-ruby-2.7
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
      - docker-compose#v4.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
    env:
      RUBY_VERSION: "2.7"

