steps:

  - label: ':docker: Build CI image for Ruby 2.7'
    timeout_in_minutes: 30
    key: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v4.7.0:
          build:
            - ci-ruby-2.7
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
      - docker-compose#v4.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2.7
    env:
      RUBY_VERSION: "2.7"

  - label: ':docker: Push W3C Docker image for branch'
    key: push-branch-cli
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2-7"
    plugins:
      - docker-compose#v4.7.0:
          build: cli
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v4.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - label: 'BitBar web browser test - Firefox latest'
    depends_on: "push-branch-cli"
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: browser-tests-bitbar
        run: browser-tests-bitbar
        service-ports: true
        use-aliases: true
        verbose: true
        command:
          - "--farm=bb"
          - "--browser=firefox_latest"
          - "--aws-public-ip"
          - "--no-tunnel"
    env:
      RUBY_VERSION: "2.7"
    concurrency: 5
    concurrency_group: 'bitbar-web'
    concurrency_method: eager


  - label: 'BitBar web browser test - Safari 15'
    depends_on: "push-branch-cli"
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: browser-tests-bitbar
        run: browser-tests-bitbar
        service-ports: true
        use-aliases: true
        verbose: true
        command:
          - "--farm=bb"
          - "--browser=safari_15"
          - "--aws-public-ip"
          - "--no-tunnel"
    env:
      RUBY_VERSION: "2.7"
    concurrency: 5
    concurrency_group: 'bitbar-web'
    concurrency_method: eager

  - label: 'BitBar web browser test - Safari 16'
    depends_on: "push-branch-cli"
    timeout_in_minutes: 10
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: browser-tests-bitbar
        run: browser-tests-bitbar
        service-ports: true
        use-aliases: true
        verbose: true
        command:
          - "--farm=bb"
          - "--browser=safari_16"
          - "--aws-public-ip"
          - "--no-tunnel"
    env:
      RUBY_VERSION: "2.7"
    concurrency: 5
    concurrency_group: 'bitbar-web'
    concurrency_method: eager
