steps:

  - label: ':docker: Build CI image for Ruby 3'
    timeout_in_minutes: 30
    key: "ci-image-ruby-3"
    plugins:
      - docker-compose#v4.14.0:
          build:
            - ci-ruby-3
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci-ruby-3:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
      - docker-compose#v4.14.0:
          push:
            - ci-ruby-3:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
    env:
      RUBY_VERSION: "3"

  - label: 'No-device tests with Ruby 3 - batch 1'
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-3"
    plugins:
      - docker-compose#v4.14.0:
          run: framework-tests
      - docker-compose#v4.14.0:
          run: comparison-tests
      - docker-compose#v4.14.0:
          run: command-workflow-tests
      - docker-compose#v4.14.0:
          run: http-response-tests
    env:
      RUBY_VERSION: "3"
    command: 'bundle exec maze-runner'
