steps:
  - label: 'Unit tests'
    plugins:
      docker-compose#v3.7.0:
        run: unit-test
    command: 'bundle exec rake'

  - label: ':docker: Build CI image'
    key: "ci-image"
    plugins:
      - docker-compose#v3.7.0:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci
      - docker-compose#v3.7.0:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - label: ':docker: Push Docker image for branch'
    key: "cli-image"
    depends_on: "ci-image"
    plugins:
      - docker-compose#v3.7.0:
          build: cli
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - label: ':docker: Build test images'
    key: "test-images"
    depends_on: "ci-image"
    plugins:
      - docker-compose#v3.7.0:
          build:
            - comparison-tests
            - android-appium-test
            - ios-appium-test
            - payload-helper-tests
            - http-response-tests
            - unit-test
            - docker-tests
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci
          build-parallel: true

  - label: 'No-device tests'
    depends_on: "test-images"
    plugins:
      - docker-compose#v3.7.0:
          run: framework-tests
      - docker-compose#v3.7.0:
          run: comparison-tests
      - docker-compose#v3.7.0:
          run: proxy-tests
      - docker-compose#v3.7.0:
          run: cli-tests
      - docker-compose#v3.7.0:
          run: http-response-tests
      - docker-compose#v3.7.0:
          run: payload-helper-tests
      - docker-compose#v3.7.0:
          run: docker-tests
    command: 'bundle exec maze-runner'

  - label: 'AWS - SAM tests'
    agents:
      queue: 'opensource-mac-aws-sam'
    command: >-
      cd test/fixtures/aws-sam &&
      bundle install &&
      bundle exec maze-runner
      --no-log-requests

  - label: 'Browserstack app-automate test - Android 6'
    depends_on: "test-images"
    plugins:
      docker-compose#v3.7.0:
        run: android-appium-test
    command: >-
      bundle exec maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_6_0
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: 'Browserstack app-automate test - Android 11'
    depends_on: "test-images"
    plugins:
      docker-compose#v3.7.0:
        run: android-appium-test
    command: >-
      bundle exec maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=bs
      --device=ANDROID_11_0
    concurrency: 9
    concurrency_group: 'browserstack-app'

  - label: 'SauceLabs Android app test'
    depends_on: "test-images"
    plugins:
      docker-compose#v3.7.0:
        run: android-appium-test
    command: >-
      bundle exec maze-runner
      --app=app/build/outputs/apk/release/app-release.apk
      --farm=sl
      --os=Android
      --device=".*Pixel 3.*"
    concurrency: 2
    concurrency_group: 'sl-app'

  - label: 'SauceLabs iOS app test'
    depends_on: "test-images"
    plugins:
      docker-compose#v3.7.0:
        run: ios-appium-test
    command: >-
      bundle exec maze-runner
      --app=iOSTestApp.ipa
      --farm=sl
      --os=iOS
      --device="iPhone 6S.*"
    concurrency: 2
    concurrency_group: 'sl-app'

  - wait

  - label: 'Update docs'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      docker-compose#v3.7.0:
        run: docs
    command: 'bundle exec rake docs:build_and_publish'

    # Release images are pushed to their own repository so that they don't get aged off.
  - label: 'Push Docker image for tag'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      - docker-compose#v3.7.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v5-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli
