steps:
  - label: ':docker: Build'
    plugins:
      - docker-compose#v2.5.1:
          build: ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from: ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BUILDKITE_BRANCH:-[latest]}
      - docker-compose#v2.5.1:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BUILDKITE_BRANCH}

  - wait

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'bundle exec rake'

  - wait

  - label: 'Release'
    plugins:
      - docker-compose#v2.5.1:
          build: cli
          cache-from: cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BUILDKITE_BRANCH:-[latest]}
      - docker-compose#v2.5.1:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BUILDKITE_BRANCH}