steps:

  - label: 'Audit current licenses'
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    command: ./scripts/license_finder.sh

  - label: ':docker: Build CI image for Ruby 2'
    timeout_in_minutes: 30
    key: "ci-image-ruby-2"
    plugins:
      - docker-compose#v4.14.0:
          build:
            - ci-ruby-2
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci-ruby-2:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2
      - docker-compose#v4.14.0:
          push:
            - ci-ruby-2:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-2
    env:
      RUBY_VERSION: "2"

  - label: ':docker: Build CI image for Ruby 3'
    timeout_in_minutes: 30
    key: "ci-image-ruby-3"
    plugins:
      - docker-compose#v4.14.0:
          build:
            - ci-ruby-3
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci-ruby-3:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
      - docker-compose#v4.14.0:
          push:
            - ci-ruby-3:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-3
    env:
      RUBY_VERSION: "3"

  - label: ':docker: Push W3C CLI image for branch'
    key: push-branch-cli
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2"
    plugins:
      - docker-compose#v4.14.0:
          build: cli
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli
      - docker-compose#v4.14.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli

  - label: ':docker: Push Legacy CLI image for branch'
    key: push-branch-cli-legacy
    timeout_in_minutes: 30
    depends_on: "ci-image-ruby-2"
    plugins:
      - docker-compose#v4.14.0:
          build: cli-legacy
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli-legacy
      - docker-compose#v4.14.0:
          push:
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli-legacy

  - label: "Triggering test pipeline with plugin"
    depends_on:
      - push-branch-cli
      - push-branch-cli-legacy
    plugins:
      - monorepo-diff#v1.0.1:
          watch:
            - path:
                - .buildkite/*
                - lib/**/*
                - bin/*
                - test/**/*
                - dockerfiles/*
              config:
                command: "buildkite-agent pipeline upload .buildkite/test_pipeline.yml"

  - wait

  - label: 'Update docs'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      docker-compose#v4.14.0:
        run: docs
    command: 'bundle exec rake docs:build_and_publish'

    # Release images are pushed to their own repository so that they don't get aged off.
  - label: 'Push Docker image for tag'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    plugins:
      - docker-compose#v4.14.0:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v9-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:${BUILDKITE_TAG}-cli-legacy
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v9-cli-legacy
            - cli-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-cli-legacy

  - label: 'Push to RubyGems.org'
    if: build.tag =~ /^v[2-9]\.[0-9]+\.[0-9]+\$/
    agents:
      queue: macos-14
    commands:
      - 'gem build bugsnag-maze-runner.gemspec'
      - 'gem push bugsnag-maze-runner-*.gem'
