steps:
  - label: ':docker: Build CI image'
    plugins:
      - docker-compose#v2.5.1:
          build:
            - ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-ci
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - wait

  - label: ':docker: Build test images'
    plugins:
      - docker-compose#v2.5.1:
          build:
            - comparison-tests
            - browserstack-app-automate
            - payload-helper-tests
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner
          build-parallel: true
          cache-from:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-ci
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - label: ':docker: Push CI'
    plugins:
      - docker-compose#v2.5.1:
          push:
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-ci
            - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci

  - wait

  - label: 'Unit tests'
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'bundle exec rake'

  - label: 'Comparison tests'
    plugins:
      docker-compose#v2.5.1:
        run: comparison-tests
    command: 'bundle exec bugsnag-maze-runner'

  - label: 'Browserstack-app-automate integration test'
    plugins:
      docker-compose#v2.5.1:
        run: browserstack-app-automate
    command: 'bundle exec bugsnag-maze-runner'
    concurrency: 5
    concurrency_group: 'browserstack-app'

  - label: 'Payload helper tests'
    plugins:
      docker-compose#v2.5.1:
        run: payload-helper-tests
    command: 'bundle exec bugsnag-maze-runner'

  - wait

  - label: 'Update docs'
    if: build.branch == "v2" || build.branch == "master"
    plugins:
      docker-compose#v2.5.1:
        run: ci
    command: 'bundle exec rake docs:build_and_publish'

  - label: 'Release'
    plugins:
      - docker-compose#v2.5.1:
          build: cli
          cache-from: cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME:-[latest]}-cli
      - docker-compose#v2.5.1:
          push:
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:latest-cli
            - cli:855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-cli