ARG BRANCH_NAME
FROM openjdk:8-jdk-stretch AS browserstack-app-automate-builder

RUN apt-get update
RUN apt-get install -y gradle jq

WORKDIR /sdk
RUN wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
RUN unzip sdk-tools-linux-4333796.zip

ENV PATH="${PATH}:/sdk/tools:/sdk/tools/bin"

RUN yes | sdkmanager "platform-tools" "platforms;android-28"

ENV PATH="${PATH}:/sdk/platform-tools"
ENV ANDROID_HOME="/sdk/"

WORKDIR /app
COPY . .

RUN ./gradlew app:assembleRelease

FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci AS browserstack-app-automate

COPY . /app
WORKDIR /app

COPY --from=browserstack-app-automate-builder /app/build /app/build
COPY --from=browserstack-app-automate-builder /app/app/build /app/app/build
