FROM licensefinder/license_finder

RUN apt-get update && apt-get install -y \
                      # Needed by curb (a dependency of Cucumber)
                      libcurl4-openssl-dev

WORKDIR /scan

CMD /scan/scripts/license_finder.sh
