ARG BRANCH_NAME
ARG RUBY_VERSION
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:${BRANCH_NAME}-ci-ruby-${RUBY_VERSION}

WORKDIR /app
COPY features features
COPY iOSTestApp.ipa iOSTestApp.ipa

