#!/usr/bin/env node

console.log("Starting error script")

const readline = require("readline")
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
})

rl.question("Input anything to error ", function(repeater) {
    throw("Oh no it's all gone wrong")
})
